// Runs the full non-DB backend test suite (everything covered by `npm test`
// except test/schema-privacy.test.mjs and test/server.test.mjs, which run as
// separate direct-execution steps before this one).
//
// This file exists because listing all of these paths as literal arguments
// directly in package.json's own "test" script string (as `node --test
// path1 path2 ...`) grows the WHOLE npm-invoked command line -- on Windows,
// npm scripts run via `cmd.exe /d /s /c "<script>"`, so the entire script
// string is one command-line argument to cmd.exe, subject to its ~8191-
// character limit. This suite crossed that limit once enough test files
// accumulated (a real failure this fixes, not a hypothetical one: adding 16
// legitimate, previously-orphaned test files to the inline list took it from
// ~8100 to 8824 characters and broke `npm test` outright). Listing the files
// here instead and spawning node with an argv array (no shell) is not
// subject to that limit -- OS process-creation argv limits are far higher.
//
// Keep this list in sync with test:db's own file list only in spirit: DB-
// backed *.mysql.test.mjs files belong in test:db (package.json), never here.
//
// You do not have to remember to update this list. test/meta/
// testSuiteRegistration.test.mjs -- itself registered below -- fails the suite
// whenever a non-DB *.test.mjs exists on disk but is missing from here, so an
// unregistered test file is a RED build rather than a silently-skipped file.
// It also fails on entries here that no longer exist on disk, on DB-backed
// paths that wandered in, and on files that would run twice.
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const backendRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const files = [
  "test/invitation/token.test.mjs",
  "test/invitation/service.test.mjs",
  "test/childprofiles/registryRepository.test.mjs",
  "test/childprofiles/service.test.mjs",
  "test/childprofiles/noReadableChildFieldsRegression.test.mjs",
  "test/http/childProfileRoutes.test.mjs",
  "test/invitation/iosEnrollmentUnavailable.test.mjs",
  "test/device/publicKey.test.mjs",
  "test/device/service.test.mjs",
  "test/relay/policy.test.mjs",
  "test/relay/service.test.mjs",
  "test/relay/noPayloadLoggingHttp.test.mjs",
  "test/recovery/policy.test.mjs",
  "test/recovery/service.test.mjs",
  "test/recovery/RecoveryEnvelopeOpener.test.mjs",
  "test/release/version.test.mjs",
  "test/release/service.test.mjs",
  "test/auth/token.test.mjs",
  "test/auth/service.test.mjs",
  "test/auth/fastifyAuthPlugin.test.mjs",
  "test/authz/service.test.mjs",
  "test/enrollment/coordinator.test.mjs",
  "test/pairing/fingerprint.test.mjs",
  "test/pairing/service.test.mjs",
  "test/deviceauth/nonce.test.mjs",
  "test/deviceauth/service.test.mjs",
  "test/familyenvelope/canonicalize.test.mjs",
  "test/familyenvelope/parse.test.mjs",
  "test/familyenvelope/replayLedger.test.mjs",
  "test/familyenvelope/dataVersionLedger.test.mjs",
  "test/familyenvelope/messageIdempotencyLedger.test.mjs",
  "test/familyenvelope/protocolCompatibility.test.mjs",
  "test/familyenvelope/policy.test.mjs",
  "test/familyenvelope/verifier.test.mjs",
  "test/familytrustset/canonicalize.test.mjs",
  "test/familytrustset/parse.test.mjs",
  "test/familytrustset/engine.test.mjs",
  "test/familytrustset/recoveryEngine.test.mjs",
  "test/familytrustset/recoveryRedTeam.test.mjs",
  "test/familytrustset/FdekRotationContract.test.mjs",
  "test/tamper/TamperStateEngine.test.mjs",
  "test/tamper/TrustedTimeHighWaterMark.test.mjs",
  "test/tamper/ReleaseIntegrityEvaluator.test.mjs",
  "test/recoverytransaction/RecoveryTransactionCoordinator.test.mjs",
  "test/usage/normalize.test.mjs",
  "test/schedule/timezone.test.mjs",
  "test/schedule/engine.test.mjs",
  "test/location/domain.test.mjs",
  "test/location/safeZone.test.mjs",
  "test/location/retention.test.mjs",
  "test/web/canonicalize.test.mjs",
  "test/web/policy.test.mjs",
  "test/web/WebRuleStore.test.mjs",
  "test/web/SignedRulePackageConsumer.test.mjs",
  "test/web/WebFilterEngine.test.mjs",
  "test/safebrowser/policy.test.mjs",
  "test/safebrowser/BlockDecisionStateStore.test.mjs",
  "test/safebrowser/ParentUnblockRequestService.test.mjs",
  "test/safebrowser/SafeBrowserNavigationPolicy.test.mjs",
  "test/youtube/policy.test.mjs",
  "test/youtube/ModeBFeatureFlagStore.test.mjs",
  "test/youtube/ModeAUsageReportService.test.mjs",
  "test/youtube/ModeBPlaybackEventService.test.mjs",
  "test/youtube/ModeTransitionService.test.mjs",
  "test/familysync/coordinator.test.mjs",
  "test/familysync/connectionState.test.mjs",
  "test/familysync/receipts.test.mjs",
  "test/familysync/sequenceProgressLedger.test.mjs",
  "test/familysync/retentionIntegration.test.mjs",
  "test/retention/calendar.test.mjs",
  "test/retention/engine.test.mjs",
  "test/retention/deleteNow.test.mjs",
  "test/retention/tombstone.test.mjs",
  "test/retention/deletionStateMachine.test.mjs",
  "test/export/pipeline.test.mjs",
  "test/familyrbac/policy.test.mjs",
  "test/familyrbac/TrustSetRoleResolver.test.mjs",
  "test/familyrbac/ActionIdempotencyLedger.test.mjs",
  "test/familyrbac/ParentActionAuthorizationService.test.mjs",
  "test/familyrbac/FamilyRbacPolicyConfigStore.test.mjs",
  "test/familymembers/service.test.mjs",
  "test/familyrbac/FamilyAuditStore.test.mjs",
  "test/familyrbac/auditWiring.test.mjs",
  "test/retention/retentionRoutes.test.mjs",
  "test/childprofiles/ChildProfileMembershipResolver.test.mjs",
  "test/childrequests/ChildRequestService.test.mjs",
  "test/childrequests/BonusGrantLedger.test.mjs",
  "test/parentpanel/DashboardAggregatorService.test.mjs",
  "test/parentpanel/WebFilteringDashboardCardProvider.test.mjs",
  "test/parentpanel/YouTubeDashboardCardProvider.test.mjs",
  "test/model/policy.test.mjs",
  "test/model/PackageVerificationGate.test.mjs",
  "test/model/ModelLifecycleService.test.mjs",
  "test/ai/policy.test.mjs",
  "test/ai/LifecycleGatedClassifier.test.mjs",
  "test/ai/WebFilterClassifierAdapter.test.mjs",
  "test/ai/privacy.test.mjs",
  "test/i18n/BidiUtils.test.mjs",
  "test/i18n/translate.test.mjs",
  "test/runtime-sync/backoff.test.mjs",
  "test/runtime-sync/priority.test.mjs",
  "test/runtime-sync/envelopeWireCodec.test.mjs",
  "test/runtime-sync/DeviceSessionService.test.mjs",
  "test/runtime-sync/OutboundRelayService.test.mjs",
  "test/runtime-sync/InboundReconnectService.test.mjs",
  "test/runtime-sync/flapping.test.mjs",
  "test/runtime-sync/http/runtimeSyncRoutes.test.mjs",
  "test/http/parentRuntimeSyncRoutes.test.mjs",
  "test/runtime-sync/RejectingCryptoVerifiers.test.mjs",
  "test/runtime-sync/http/productionCryptoGateFailClosed.test.mjs",
  "test/platformadmin/policy.test.mjs",
  "test/platformadmin/rbacPolicy.test.mjs",
  "test/platformadmin/totp.test.mjs",
  "test/platformadmin/passwordCredential.test.mjs",
  "test/platformadmin/token.test.mjs",
  "test/platformadmin/auditTypes.test.mjs",
  "test/platformadmin/authService.test.mjs",
  "test/platformadmin/accountService.test.mjs",
  "test/platformadmin/fastifyPlatformAdminAuthPlugin.test.mjs",
  "test/platformadmin/crossRealm.test.mjs",
  "test/platformadmin/privacy.test.mjs",
  "test/entitlements/priceBookVersion.test.mjs",
  "test/billing/money.test.mjs",
  "test/billing/currency.test.mjs",
  "test/billing/market.test.mjs",
  "test/billing/rbac.test.mjs",
  "test/billing/validation.test.mjs",
  "test/billing/providerContract.test.mjs",
  "test/billing/schemaPrivacy.test.mjs",
  "test/billing/quoteBridge.test.mjs",
  "test/billing/providerRegistry.test.mjs",
  "test/billing/sandboxProvider.test.mjs",
  "test/billing/familyCommercialAuthorityResolver.test.mjs",
  "test/billing/refundOperationsSchemaPrivacy.test.mjs",
  "test/platformadmin/operational/pagination.test.mjs",
  "test/platformadmin/operational/dto.test.mjs",
  "test/platformadmin/operational/privilegeGate.test.mjs",
  "test/platformadmin/operational/schemaPrivacyScan.test.mjs",
  "test/platformadmin/operational/httpAuthzBoundary.test.mjs",
  "test/entitlements/priceBookQuotePort.test.mjs",
  "test/familycommercial/authorization.test.mjs",
  "test/familycommercial/dto.test.mjs",
  "test/familycommercial/familyCommercialService.test.mjs",
  "test/familycommercial/familyCommercialRoutes.test.mjs",
  "test/familycommercial/authority/canonicalize.test.mjs",
  "test/familycommercial/authority/FamilyOwnerAttestationChainEngine.test.mjs",
  "test/authz/commercialNotificationsPolicy.test.mjs",
  "test/commercialnotifications/publisher.test.mjs",
  "test/commercialnotifications/schemaPrivacy.test.mjs",
  "test/commercialnotifications/renewalUpcomingSchemaPrivacy.test.mjs",
  "test/commercialnotifications/service.test.mjs",
  "test/parentaccount/service.test.mjs",
  "test/parentaccount/routes.test.mjs",
  "test/parentaccount/e2e.registrationToOwnerMutation.test.mjs",
  "test/entitlements/complimentaryGrantValidation.test.mjs",
  "test/platformadmin/complimentaryRbacPolicy.test.mjs",
  "test/platformadmin/complimentaryAuditTypes.test.mjs",
  "test/commercialmaintenance/config.test.mjs",
  "test/parentaccount/freeaccess/deriveFreeAccessStatus.test.mjs",
  "test/parentaccount/freeaccess/adjustment.test.mjs",
  "test/parentaccount/freeaccess/FreeAccessAdminService.test.mjs",
  "test/parentaccount/freeAccessStatusRoute.test.mjs",
  "test/billing/settlement.test.mjs",
  "test/platformadmin/settlementRbacPolicy.test.mjs",
  "test/billing/loggingPrivacy.test.mjs",
  "test/security/checkNoAdTrackingSdks.test.mjs",
  "test/security/sdkDisclosure.test.mjs",
  "test/security/noTelemetryEndpoint.test.mjs",
  "test/retention/types.test.mjs",
  "test/familyrbac/RemovalDecisionAuthority.test.mjs",
  "test/familyrbac/RemovalDecisionAuthority.deviceRevocation.test.mjs",
  "test/familyrbac/RealProtectiveAuthorityResolver.test.mjs",
  "test/familyrbac/removalDecisionRoutes.wiring.test.mjs",
  "test/http/buildServer.removalDecisionAndSafeZoneWiring.test.mjs",
  "test/http/buildServerRateLimiting.test.mjs",
  "test/tooling/RebuildR3DerivedLedgers.test.mjs",
  "test/alerts/ProtectionAlert.test.mjs",
  "test/alerts/ProtectionAlertProducer.test.mjs",
  "test/alerts/RejectingOpaqueProtectionAlertComposer.test.mjs",
  "test/device/BrowserEndpointService.test.mjs",
  "test/http/browserEndpointRoutes.test.mjs",
  "test/http/childRequestRoutes.test.mjs",
  "test/http/childPolicyRoutes.test.mjs",
  "test/http/familyMemberRoutes.test.mjs",
  "test/familyrbac/FamilyAuditEventProducer.test.mjs",
  "test/familyrbac/auditEventDelivery.wiring.test.mjs",
  "test/http/familyAuditEventRoutes.test.mjs",
  "test/http/protectionAlertRoutes.test.mjs",
  "test/eyeprotection/EyeProtectionSettingsService.test.mjs",
  "test/http/eyeProtectionRoutes.test.mjs",
  "test/http/webRuleRoutes.test.mjs",
  "test/http/dashboardRoutes.test.mjs",
  "test/platformadmin/operational/releaseRoutes.test.mjs",
  "test/platformadmin/operational/billingAdminRoutes.test.mjs",
  "test/enrollment/AdministrationPersistenceSchema.test.mjs",
  "test/enrollment/AdministrationPinService.test.mjs",
  "test/enrollment/slotConsumption.test.mjs",
  "test/entitlements/FreeAccessAcquisitionCallSites.test.mjs",
  "test/http/cors.test.mjs",
  "test/runtime/gracefulShutdown.test.mjs",
  "test/retention/serverCiphertextTtl.test.mjs",
  "test/tooling/migrationAdvisoryLock.test.mjs",
  "test/invitation/enrollmentProfile.test.mjs",
  "test/location/safeZoneRepository.test.mjs",
  "test/mutation/privacyBoundaries.test.mjs",
  "test/parentaccount/freeaccess/FreeAccessAcquisitionPolicy.test.mjs",
  "test/parentaccount/preferencesSafeZonesRoute.test.mjs",
  "test/parentaccount/preferencesSafeZonesSchema.test.mjs",
  "test/runtime-schedule-conformance/evaluationVectors.test.mjs",
  "test/runtime-schedule-conformance/policyAcceptanceVectors.test.mjs",
  "test/tamper/TrustedTimeTamperBridge.test.mjs",
  "test/telemetry/consent.test.mjs",
  "test/youtube/SafeContentCapability.test.mjs",
  // Guards this very list: fails if any non-DB *.test.mjs exists on disk but is
  // absent from it (see test/meta/testSuiteRegistration.test.mjs for why the
  // list stayed hand-maintained instead of becoming a glob).
  "test/meta/testSuiteRegistration.test.mjs",
];

const result = spawnSync(process.execPath, ['--test', ...files], {
  cwd: backendRoot,
  stdio: 'inherit',
});

process.exit(result.status ?? 1);
