-- docs/database/bootstrap/PCA_MYSQL_8_4_DISPOSABLE_VERIFY.sql
-- GENERATED by backend/scripts/generate-disposable-bootstrap.mjs. Do not hand-edit.
--
-- Run this AFTER executing PCA_MYSQL_8_4_DISPOSABLE_BOOTSTRAP.sql, against the
-- same database, to confirm what actually landed.
--
-- WHERE THE EXPECTED NUMBERS COME FROM. Every one is COMPUTED from
-- backend/src/db/schema.ts (PCA_CANONICAL_SCHEMA) and from the actual
-- filenames in backend/migrations/, at generation time -- not typed in by
-- hand and not copied from a previous report. Regenerating this file after a
-- schema change updates them automatically; if they ever disagree with the
-- repository, the generator's own --check mode fails.
--
-- Every row of the RESULT column must read PASS.

SELECT 'PCA MySQL 8.4 disposable bootstrap verification' AS report, DATABASE() AS `database`, VERSION() AS server_version;

SELECT
  check_name,
  expected,
  actual,
  CASE WHEN expected = actual THEN 'PASS' ELSE 'FAIL' END AS result
FROM (
  SELECT 'tables'                   AS check_name, 78 AS expected,
         (SELECT COUNT(*) FROM information_schema.tables
            WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE') AS actual
  UNION ALL SELECT 'columns', 646,
         (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE())
  UNION ALL SELECT 'primary keys', 78,
         (SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE table_schema = DATABASE() AND constraint_type = 'PRIMARY KEY')
  UNION ALL SELECT 'foreign keys', 83,
         (SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE table_schema = DATABASE() AND constraint_type = 'FOREIGN KEY')
  UNION ALL SELECT 'unique non-PK indexes', 32,
         (SELECT COUNT(*) FROM (SELECT DISTINCT table_name, index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE() AND non_unique = 0 AND index_name <> 'PRIMARY') u)
  UNION ALL SELECT 'non-unique indexes', 119,
         (SELECT COUNT(*) FROM (SELECT DISTINCT table_name, index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE() AND non_unique = 1) n)
  UNION ALL SELECT 'CHECK constraints', 233,
         (SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE table_schema = DATABASE() AND constraint_type = 'CHECK')
  UNION ALL SELECT 'schema_migrations rows', 38,
         (SELECT COUNT(*) FROM `schema_migrations`)
  UNION ALL SELECT 'views (must be 0)', 0,
         (SELECT COUNT(*) FROM information_schema.tables
            WHERE table_schema = DATABASE() AND table_type = 'VIEW')
  UNION ALL SELECT 'triggers (must be 0)', 0,
         (SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema = DATABASE())
  UNION ALL SELECT 'routines (must be 0)', 0,
         (SELECT COUNT(*) FROM information_schema.routines WHERE routine_schema = DATABASE())
) AS checks;

-- Journal endpoints, so a truncated paste is visible rather than silent.
SELECT
  '0001_mysql_baseline.sql' AS expected_first, MIN(version) AS actual_first,
  '0040_delete_now_ledger.sql' AS expected_last,  MAX(version) AS actual_last,
  CASE WHEN MIN(version) = '0001_mysql_baseline.sql' AND MAX(version) = '0040_delete_now_ledger.sql' THEN 'PASS' ELSE 'FAIL' END AS result
FROM `schema_migrations`;

-- Environment, which PCA pins independently of the schema. MySQL must be
-- exactly 8.4.x (backend/scripts/verify-mysql.mjs enforces the same bar).
SELECT
  VERSION() AS server_version,
  @@global.time_zone AS global_time_zone,
  (SELECT default_character_set_name FROM information_schema.schemata WHERE schema_name = DATABASE()) AS `charset`,
  (SELECT default_collation_name    FROM information_schema.schemata WHERE schema_name = DATABASE()) AS collation,
  CASE
    WHEN VERSION() NOT LIKE '8.4.%' THEN 'FAIL: PCA requires exactly MySQL 8.4.x'
    WHEN (SELECT default_collation_name FROM information_schema.schemata WHERE schema_name = DATABASE()) <> 'utf8mb4_bin'
      THEN 'FAIL: database collation must be utf8mb4_bin'
    ELSE 'PASS'
  END AS result;

-- No application or business data may exist in a freshly bootstrapped
-- database. A non-zero count here means something seeded it.
SELECT 'no application data' AS check_name, 0 AS expected,
  (SELECT COUNT(*) FROM `families`)
  + (SELECT COUNT(*) FROM `parent_accounts`)
  + (SELECT COUNT(*) FROM `devices`)
  + (SELECT COUNT(*) FROM `enrollment_invitations`)
  + (SELECT COUNT(*) FROM `licenses`) AS actual,
  CASE WHEN (SELECT COUNT(*) FROM `families`)
          + (SELECT COUNT(*) FROM `parent_accounts`)
          + (SELECT COUNT(*) FROM `devices`)
          + (SELECT COUNT(*) FROM `enrollment_invitations`)
          + (SELECT COUNT(*) FROM `licenses`) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;
