// Client-side mirror of backend/src/platformadmin/auth/rbacPolicy.ts's
// Section 3.7 permission matrix. This copy exists ONLY to hide/disable
// unauthorized actions for usability (mission Section 8) -- it is never
// the authority. Every mutating request still requires the server to
// independently authorize it; a UI bug here can make a button visible that
// a subsequent server call correctly rejects, but it can never grant real
// access. See docs/implementation/addenda/PCA_ADDENDUM_002_PLATFORM_ADMINISTRATION_BILLING.md
// Section 3.7 for the authoritative table this mirrors.

export type PlatformAdminRole =
  | 'APP_OWNER'
  | 'PLATFORM_ADMIN'
  | 'FINANCE_ADMIN'
  | 'SUPPORT_ADMIN'
  | 'AUDITOR_READ_ONLY';

export const PLATFORM_ADMIN_ROLES: readonly PlatformAdminRole[] = [
  'APP_OWNER',
  'PLATFORM_ADMIN',
  'FINANCE_ADMIN',
  'SUPPORT_ADMIN',
  'AUDITOR_READ_ONLY',
];

export type PlatformAdminOperation =
  | 'MANAGE_ADMIN_ACCOUNTS'
  | 'ASSIGN_ADMIN_ROLE'
  | 'VIEW_ADMIN_ACCOUNTS'
  | 'SUSPEND_FAMILY_ACCOUNT'
  | 'REACTIVATE_FAMILY_ACCOUNT'
  | 'ADMINISTER_ENTITLEMENT_QUANTITY'
  | 'ADMINISTER_BILLING'
  | 'ISSUE_REFUND'
  | 'ADMINISTER_SETTLEMENT'
  | 'ADMINISTER_SENSITIVE_PLATFORM_SETTINGS'
  | 'ADMINISTER_NONSENSITIVE_PLATFORM_SETTINGS'
  | 'VIEW_PLATFORM_DASHBOARD'
  | 'VIEW_AUDIT_LOG_FULL'
  | 'VIEW_AUDIT_LOG_OWN'
  | 'VIEW_SUPPORT_ACCOUNT_METADATA'
  | 'PERFORM_SUPPORT_ACTION'
  // PCA-ADD-COMP-014: complimentary-grant create/revoke/renew (bounded
  // delegation) and the permanent/lifetime-grant restriction (APP_OWNER
  // only). Mirrors backend/src/platformadmin/auth/rbacPolicy.ts exactly.
  | 'ADMINISTER_COMPLIMENTARY_GRANT'
  | 'ADMINISTER_COMPLIMENTARY_GRANT_PERMANENT';

type Verdict = 'ALLOW' | 'DENY';

const OPERATION_MATRIX: Record<PlatformAdminOperation, Record<PlatformAdminRole, Verdict>> = {
  MANAGE_ADMIN_ACCOUNTS: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ASSIGN_ADMIN_ROLE: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  VIEW_ADMIN_ACCOUNTS: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'ALLOW' },
  SUSPEND_FAMILY_ACCOUNT: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  REACTIVATE_FAMILY_ACCOUNT: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_ENTITLEMENT_QUANTITY: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_BILLING: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ISSUE_REFUND: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_SETTLEMENT: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_SENSITIVE_PLATFORM_SETTINGS: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_NONSENSITIVE_PLATFORM_SETTINGS: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  VIEW_PLATFORM_DASHBOARD: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'ALLOW', AUDITOR_READ_ONLY: 'ALLOW' },
  VIEW_AUDIT_LOG_FULL: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'ALLOW' },
  VIEW_AUDIT_LOG_OWN: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'ALLOW', AUDITOR_READ_ONLY: 'ALLOW' },
  VIEW_SUPPORT_ACCOUNT_METADATA: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'ALLOW', SUPPORT_ADMIN: 'ALLOW', AUDITOR_READ_ONLY: 'ALLOW' },
  PERFORM_SUPPORT_ACTION: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'ALLOW', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_COMPLIMENTARY_GRANT: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'ALLOW', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
  ADMINISTER_COMPLIMENTARY_GRANT_PERMANENT: { APP_OWNER: 'ALLOW', PLATFORM_ADMIN: 'DENY', FINANCE_ADMIN: 'DENY', SUPPORT_ADMIN: 'DENY', AUDITOR_READ_ONLY: 'DENY' },
};

/** ALLOW if any given role maps to ALLOW for this operation; DENY (including empty roles) otherwise. UI hint only -- see file header. */
export function isPermitted(roles: readonly PlatformAdminRole[], operation: PlatformAdminOperation): boolean {
  const row = OPERATION_MATRIX[operation];
  return roles.some((role) => row[role] === 'ALLOW');
}

export function isKnownRole(value: unknown): value is PlatformAdminRole {
  return typeof value === 'string' && (PLATFORM_ADMIN_ROLES as readonly string[]).includes(value);
}
