-- database/live-bootstrap/02_reference_data.sql
-- GENERATED by backend/scripts/generate-bootstrap-reference-data.mjs.
-- Do not hand-edit -- see that script's header for what belongs here and why.
--
-- Idempotent-safe: every INSERT below targets a table this bootstrap just
-- created empty, in the same one-time run as 01_create_database_schema.sql.
-- This file must never be re-run against a database that already holds
-- these rows.

-- =========================================================================
-- 1. Bootstrap bookkeeping: mark every accepted migration as already
--    applied, so the next `npm run db:migrate` only applies NEW migrations
--    (0037+) going forward -- see this script's header.
-- =========================================================================
INSERT INTO `schema_migrations` (`version`, `applied_at`) VALUES
  ('0001_mysql_baseline.sql', CURRENT_TIMESTAMP(3)),
  ('0002_sync_durability.sql', CURRENT_TIMESTAMP(3)),
  ('0003_enrollment_bootstrap_attempts.sql', CURRENT_TIMESTAMP(3)),
  ('0004_envelope_ledger_family_scope.sql', CURRENT_TIMESTAMP(3)),
  ('0005_platform_admin_identity_rbac_audit.sql', CURRENT_TIMESTAMP(3)),
  ('0006_platform_entitlements_enrollment_limits.sql', CURRENT_TIMESTAMP(3)),
  ('0007_billing_core.sql', CURRENT_TIMESTAMP(3)),
  ('0008_payment_orchestration.sql', CURRENT_TIMESTAMP(3)),
  ('0011_family_commercial_authority.sql', CURRENT_TIMESTAMP(3)),
  ('0012_commercial_notifications.sql', CURRENT_TIMESTAMP(3)),
  ('0013_parent_account_identity.sql', CURRENT_TIMESTAMP(3)),
  ('0014_complimentary_entitlement_grants.sql', CURRENT_TIMESTAMP(3)),
  ('0015_settlement_reconciliation.sql', CURRENT_TIMESTAMP(3)),
  ('0016_invitation_lifecycle_states.sql', CURRENT_TIMESTAMP(3)),
  ('0017_platform_admin_settings_family_status.sql', CURRENT_TIMESTAMP(3)),
  ('0018_settlement_usd_normalization.sql', CURRENT_TIMESTAMP(3)),
  ('0019_enrollment_profile_contract.sql', CURRENT_TIMESTAMP(3)),
  ('0020_parent_preferences_safe_zones.sql', CURRENT_TIMESTAMP(3)),
  ('0021_platform_admin_security_alerts.sql', CURRENT_TIMESTAMP(3)),
  ('0022_enrollment_administration_persistence.sql', CURRENT_TIMESTAMP(3)),
  ('0023_removal_decision_authority_persistence.sql', CURRENT_TIMESTAMP(3)),
  ('0024_device_protection_status.sql', CURRENT_TIMESTAMP(3)),
  ('0025_protection_alerts.sql', CURRENT_TIMESTAMP(3)),
  ('0026_browser_endpoint_registration.sql', CURRENT_TIMESTAMP(3)),
  ('0027_family_member_invitations.sql', CURRENT_TIMESTAMP(3)),
  ('0028_family_audit_events.sql', CURRENT_TIMESTAMP(3)),
  ('0029_parent_password_reset_codes.sql', CURRENT_TIMESTAMP(3)),
  ('0030_verification_code_credential_binding.sql', CURRENT_TIMESTAMP(3)),
  ('0031_billing_subscription_auto_renew.sql', CURRENT_TIMESTAMP(3)),
  ('0032_eye_protection_settings.sql', CURRENT_TIMESTAMP(3)),
  ('0033_commercial_notifications_renewal_upcoming.sql', CURRENT_TIMESTAMP(3)),
  ('0034_audit_alert_ciphertext_expiry.sql', CURRENT_TIMESTAMP(3)),
  ('0035_family_member_invitation_pending_uniqueness.sql', CURRENT_TIMESTAMP(3)),
  ('0036_family_child_memberships.sql', CURRENT_TIMESTAMP(3));

-- =========================================================================
-- 2. Production reference data (from backend/migrations/0007_billing_core.sql)
-- =========================================================================
INSERT INTO `billing_currencies` (`currency_code`, `minor_unit_exponent`, `enabled`) VALUES
  ('USD', 2, 1),
  ('SAR', 2, 1),
  ('YER', 2, 1);

INSERT INTO `billing_commercial_markets` (`commercial_market`, `default_currency_code`) VALUES
  ('YEMEN', 'YER'),
  ('GULF', 'SAR'),
  ('GLOBAL_OTHER', 'USD');

INSERT INTO `billing_country_market_rules` (`country_code`, `commercial_market`) VALUES
  ('YE', 'YEMEN'),
  ('SA', 'GULF'),
  ('AE', 'GULF'),
  ('QA', 'GULF'),
  ('KW', 'GULF'),
  ('BH', 'GULF'),
  ('OM', 'GULF');

-- =========================================================================
-- 3. Production reference data (from backend/migrations/0006_platform_entitlements_enrollment_limits.sql)
-- =========================================================================
INSERT INTO `entitlement_defaults` (`tier`, `parent_member_limit`, `managed_device_limit`, `updated_at`, `updated_by_admin_id`) VALUES
  ('FREE_STARTER', 1, 1, CURRENT_TIMESTAMP(3), NULL);
